"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('course', [
      {
        courseName: "Learn JavaScript - Full Course for Beginners",
        courseDescription: "This course is an all-encompassing software engineering course that offers 1:1 mentorship and classes taught by development expert Colt Steele. Coursework ranges from front-end and back-end development to production-ready web app development. ",
        courseCategoryId: 4,
        courseCover: "https://res.cloudinary.com/dvaeob3pw/image/upload/v1715533051/Mooc/courses/1/cover.png",
        teacherId: 1,
      },
      {
        courseName: "Test2",
        courseDescription: "TestDescription2",
        courseCategoryId: 8,
        courseCover: "Cover URL",
        teacherId: 2,
      },
      {
        courseName: "Test3",
        courseDescription: "TestDescription3",
        courseCategoryId: 5,
        courseCover: "Cover URL",
        teacherId: 3,
      },
      {
        courseName: "Test4",
        courseDescription: "TestDescription4",
        courseCategoryId: 5,
        courseCover: "Cover URL",
        teacherId: 4,
      },
      {
        courseName: "Test5",
        courseDescription: "TestDescription5",
        courseCategoryId: 7,
        courseCover: "Cover URL",
        teacherId: 5,
      },
      {
        courseName: "Test6",
        courseDescription: "TestDescription6",
        courseCategoryId: 4,
        courseCover: "Cover URL",
        teacherId: 6,
      },
      {
        courseName: "Test7",
        courseDescription: "TestDescription7",
        courseCategoryId: 2,
        courseCover: "Cover URL",
        teacherId: 1,
      },
      {
        courseName: "Test8",
        courseDescription: "TestDescription8",
        courseCategoryId: 10,
        courseCover: "Cover URL",
        teacherId: 2,
      },
      {
        courseName: "Test9",
        courseDescription: "TestDescription9",
        courseCategoryId: 9,
        courseCover: "Cover URL",
        teacherId: 3,
      },
      {
        courseName: "Test10",
        courseDescription: "TestDescription10",
        courseCategoryId: 19,
        courseCover: "Cover URL",
        teacherId: 4,
      },
      {
        courseName: "Test11",
        courseDescription: "TestDescription11",
        courseCategoryId: 17,
        courseCover: "Cover URL",
        teacherId: 5,
      },
      {
        courseName: "Test12",
        courseDescription: "TestDescription12",
        courseCategoryId: 15,
        courseCover: "Cover URL",
        teacherId: 6,
      },
      {
        courseName: "Test13",
        courseDescription: "TestDescription13",
        courseCategoryId: 17,
        courseCover: "Cover URL",
        teacherId: 1,
      },
      {
        courseName: "Test14",
        courseDescription: "TestDescription14",
        courseCategoryId: 2,
        courseCover: "Cover URL",
        teacherId: 2,
      },
      {
        courseName: "Test15",
        courseDescription: "TestDescription15",
        courseCategoryId: 9,
        courseCover: "Cover URL",
        teacherId: 3,
      },
      {
        courseName: "Test16",
        courseDescription: "TestDescription16",
        courseCategoryId: 13,
        courseCover: "Cover URL",
        teacherId: 4,
      },
      {
        courseName: "Test17",
        courseDescription: "TestDescription17",
        courseCategoryId: 7,
        courseCover: "Cover URL",
        teacherId: 5,
      },
      {
        courseName: "Test18",
        courseDescription: "TestDescription18",
        courseCategoryId: 3,
        courseCover: "Cover URL",
        teacherId: 6,
      },
      {
        courseName: "Test19",
        courseDescription: "TestDescription19",
        courseCategoryId: 2,
        courseCover: "Cover URL",
        teacherId: 1,
      },
      {
        courseName: "Test20",
        courseDescription: "TestDescription20",
        courseCategoryId: 19,
        courseCover: "Cover URL",
        teacherId: 2,
      },
      {
        courseName: "Test21",
        courseDescription: "TestDescription21",
        courseCategoryId: 24,
        courseCover: "Cover URL",
        teacherId: 3,
      },
      {
        courseName: "Test22",
        courseDescription: "TestDescription22",
        courseCategoryId: 1,
        courseCover: "Cover URL",
        teacherId: 4,
      },
      {
        courseName: "Test23",
        courseDescription: "TestDescription23",
        courseCategoryId: 6,
        courseCover: "Cover URL",
        teacherId: 5,
      },
      {
        courseName: "Test24",
        courseDescription: "TestDescription24",
        courseCategoryId: 12,
        courseCover: "Cover URL",
        teacherId: 6,
      },
      {
        courseName: "Test25",
        courseDescription: "TestDescription25",
        courseCategoryId: 1,
        courseCover: "Cover URL",
        teacherId: 1,
      },
      {
        courseName: "Test26",
        courseDescription: "TestDescription26",
        courseCategoryId: 7,
        courseCover: "Cover URL",
        teacherId: 2,
      },
      {
        courseName: "Test27",
        courseDescription: "TestDescription27",
        courseCategoryId: 23,
        courseCover: "Cover URL",
        teacherId: 3,
      },
      {
        courseName: "Test28",
        courseDescription: "TestDescription28",
        courseCategoryId: 16,
        courseCover: "Cover URL",
        teacherId: 4,
      },
      {
        courseName: "Test29",
        courseDescription: "TestDescription29",
        courseCategoryId: 6,
        courseCover: "Cover URL",
        teacherId: 5,
      },
      {
        courseName: "Test30",
        courseDescription: "TestDescription30",
        courseCategoryId: 20,
        courseCover: "Cover URL",
        teacherId: 6,
      },
    ], {});
    console.log("Courses seeded successfully.");
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.dropTable("course");
    console.log("Courses table dropped successfully.");
  },
};
